### ISSUE TITLE
MessageGroup

### ISSUE THREAD

**Issue by daisyroup** [alresiainc/laravel-wassenger#1]
Hello, can you help me? i want to send message with media, so i try
`$invoicePath = public_path("invoices/" . $invoiceFile);`
`Messages::messageGroup(
            '+123456789',
            'Hello ' 
        )
            ->media(['file', $invoicePath])
            ->send();`

it says 'Undefined property: stdClass::$phone'

**Comment by fidelisepeter** [comment]
> Hello, can you help me? i want to send message with media, so i try `$invoicePath = public_path("invoices/" . $invoiceFile);` `Messages::messageGroup( '+123456789', 'Hello ' ) ->media(['file', $invoicePath]) ->send();`
> 
> it says 'Undefined property: stdClass::$phone'

Hello @daisyroup 
sorry I get to you very late.
This has been fixes in [v1.2.1](https://github.com/alresiainc/laravel-wassenger/releases/tag/v1.2.1)
run 
```shell
composer update alresia/laravel-wassenger
```
to update it
thanks.

**Comment by daisyroup** [comment]
Thank you for fixing the bug
